apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  labels:
    app: helloapp
spec:
  containers:
    - name: helloapp
      image: anhdo98/hello-app:tagVersion
      ports:
        - containerPort: 8080
